apiVersion: v1
kind: Namespace
metadata:
  name: meowbernetes

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meowbernetes-deployment
  namespace: meowbernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meowbernetes
  template:
    metadata:
      labels:
        app: meowbernetes
    spec:
      containers:
        - name: meowbernetes
          image: jamesgeddes/meowbernetes
          ports:
            - containerPort: 8080

---
# meowbernetes service
# meowbernetes service
apiVersion: v1
kind: Service
metadata:
  name: meowbernetes-service
  namespace: meowbernetes
spec:
  selector:
    app: meowbernetes
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
# meowbernetes ingress
# meowbernetes ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meowbernetes-ingress
  namespace: meowbernetes
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - meowbernetes.k8s-demo.com
      secretName: meowbernetes-tls
  rules:
    - host: meowbernetes.k8s-demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meowbernetes-service
                port:
                  number: 80
